dist: xenial
addons:
  snaps:
  - name: dotnet-sdk
    classic: true
    channel: latest/beta
sudo: required

language: csharp
solution: SoluiNet.DevTools.sln

matrix: 
  include:
    - dotnet: 3.0.100-preview7-012821
      mono: none
      env: DOTNETCORE=3
    - mono: latest

script:
  - sudo snap alias dotnet-sdk.dotnet dotnet
  - dotnet --version