image: Visual Studio 2017

version: 0.9.{build}

before_build:
  - nuget restore
  - cp SoluiNet.DevTools.UI\Settings.Default.xml SoluiNet.DevTools.UI\Settings.xml
  - cp SoluiNet.DevTools.UI\ConnectionStrings.Default.config SoluiNet.DevTools.UI\ConnectionStrings.config

# build cache to preserve files/folders between builds
cache:
  - packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
  - '%LocalAppData%\NuGet\Cache'    # NuGet < v3
  - '%LocalAppData%\NuGet\v3-cache' # NuGet v3

after_build:
  - 7z a SoluiNet.DevTools-%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\SoluiNet.DevTools.UI\bin\net461\AnyCPU\Debug\*

# the following assembly info patching might be replaced with this: https://www.arthurrump.com/2017/03/17/visual-studio-2017-csproj-version-patching-in-appveyor/

# enable patching of AssemblyInfo.* files
#assembly_info:
#  patch: true
#  file: AssemblyInfo.*
#  assembly_version: "0.9.{build}"
#  assembly_file_version: "{version}"
#  assembly_informational_version: "{version}"

artifacts:
  - path: SoluiNet.DevTools-%APPVEYOR_BUILD_VERSION%.zip
    name: SoluiNet.DevTools

#environment:
#  COVERALLS_SERVICE_NAME: appveyor
#  nodejs_version: "0.10"
#  COVERALLS_REPO_TOKEN:
#  secure: W4w/2P0yaNPf9HlfJ0v6HfaJY0jR6/GjJm7cY0+0+xcWEQ7GTPNKstUL0bFCg2Mi

#test_script:
#  - npm test
#after_test:
#  - node ./node_modules/coveralls/bin/coveralls.js < ./coverage/lcov.info 