//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="SoluiNet.ConfigurationType", Namespace="http://solui.net/ConfigurationSchema.xsd")]
[System.Xml.Serialization.XmlRootAttribute("SoluiNet.Configuration", Namespace="http://solui.net/ConfigurationSchema.xsd", IsNullable=false)]
public partial class SoluiNetConfigurationType {
    
    private SoluiNetPluginType[] soluiNetPluginField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SoluiNet.Plugin")]
    public SoluiNetPluginType[] SoluiNetPlugin {
        get {
            return this.soluiNetPluginField;
        }
        set {
            this.soluiNetPluginField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="SoluiNet.PluginType", Namespace="http://solui.net/ConfigurationSchema.xsd")]
public partial class SoluiNetPluginType {
    
    private SoluiNetConfigurationEntryType[] soluiNetConfigurationEntryField;
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SoluiNet.ConfigurationEntry")]
    public SoluiNetConfigurationEntryType[] SoluiNetConfigurationEntry {
        get {
            return this.soluiNetConfigurationEntryField;
        }
        set {
            this.soluiNetConfigurationEntryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(TypeName="SoluiNet.ConfigurationEntryType", Namespace="http://solui.net/ConfigurationSchema.xsd")]
public partial class SoluiNetConfigurationEntryType {
    
    private string nameField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}
