//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.7.3081.0.
// 
namespace SoluiNet.DevTools.Core.Configuration {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="SoluiNet.ConfigurationType", Namespace="http://solui.net/ConfigurationSchema.xsd")]
    [System.Xml.Serialization.XmlRootAttribute("SoluiNet.Configuration", Namespace="http://solui.net/ConfigurationSchema.xsd", IsNullable=false)]
    public partial class SoluiNetConfigurationType {
        
        private SoluiNetPluginType[] soluiNetPluginField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SoluiNet.Plugin")]
        public SoluiNetPluginType[] SoluiNetPlugin {
            get {
                return this.soluiNetPluginField;
            }
            set {
                this.soluiNetPluginField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="SoluiNet.PluginType", Namespace="http://solui.net/ConfigurationSchema.xsd")]
    public partial class SoluiNetPluginType {
        
        private SoluiNetConfigurationEntryType[] soluiNetConfigurationEntryField;
        
        private SoluiNetEnvironmentType[] soluiNetEnvironmentField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SoluiNet.ConfigurationEntry")]
        public SoluiNetConfigurationEntryType[] SoluiNetConfigurationEntry {
            get {
                return this.soluiNetConfigurationEntryField;
            }
            set {
                this.soluiNetConfigurationEntryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SoluiNet.Environment")]
        public SoluiNetEnvironmentType[] SoluiNetEnvironment {
            get {
                return this.soluiNetEnvironmentField;
            }
            set {
                this.soluiNetEnvironmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="SoluiNet.ConfigurationEntryType", Namespace="http://solui.net/ConfigurationSchema.xsd")]
    public partial class SoluiNetConfigurationEntryType {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="SoluiNet.EnvironmentType", Namespace="http://solui.net/ConfigurationSchema.xsd")]
    public partial class SoluiNetEnvironmentType {
        
        private SoluiNetConfigurationEntryType[] soluiNetConfigurationEntryField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SoluiNet.ConfigurationEntry")]
        public SoluiNetConfigurationEntryType[] SoluiNetConfigurationEntry {
            get {
                return this.soluiNetConfigurationEntryField;
            }
            set {
                this.soluiNetConfigurationEntryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
}
