//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=4.6.1055.0.
// 
namespace SoluiNet.DevTools.Core.UI.XmlData {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="SoluiNet.BrushDefinitionType", Namespace="http://solui.net/BrushDefinition.xsd")]
    [System.Xml.Serialization.XmlRootAttribute("SoluiNet.BrushDefinition", Namespace="http://solui.net/BrushDefinition.xsd", IsNullable=false)]
    public partial class SoluiNetBrushDefinitionType {
        
        private SoluiNetPointType soluiNetStartPointField;
        
        private SoluiNetPointType soluiNetEndPointField;
        
        private SoluiNetGradientStopType[] soluiNetGradientStopField;
        
        private SoluiNetBrushType typeField;
        
        private bool typeFieldSpecified;
        
        private string startColourField;
        
        private string endColourField;
        
        private double angleField;
        
        private bool angleFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SoluiNet.StartPoint")]
        public SoluiNetPointType SoluiNetStartPoint {
            get {
                return this.soluiNetStartPointField;
            }
            set {
                this.soluiNetStartPointField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SoluiNet.EndPoint")]
        public SoluiNetPointType SoluiNetEndPoint {
            get {
                return this.soluiNetEndPointField;
            }
            set {
                this.soluiNetEndPointField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SoluiNet.GradientStop")]
        public SoluiNetGradientStopType[] SoluiNetGradientStop {
            get {
                return this.soluiNetGradientStopField;
            }
            set {
                this.soluiNetGradientStopField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public SoluiNetBrushType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string startColour {
            get {
                return this.startColourField;
            }
            set {
                this.startColourField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string endColour {
            get {
                return this.endColourField;
            }
            set {
                this.endColourField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double angle {
            get {
                return this.angleField;
            }
            set {
                this.angleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool angleSpecified {
            get {
                return this.angleFieldSpecified;
            }
            set {
                this.angleFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="SoluiNet.PointType", Namespace="http://solui.net/BrushDefinition.xsd")]
    public partial class SoluiNetPointType {
        
        private double xAxisField;
        
        private bool xAxisFieldSpecified;
        
        private double yAxisField;
        
        private bool yAxisFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double xAxis {
            get {
                return this.xAxisField;
            }
            set {
                this.xAxisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool xAxisSpecified {
            get {
                return this.xAxisFieldSpecified;
            }
            set {
                this.xAxisFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double yAxis {
            get {
                return this.yAxisField;
            }
            set {
                this.yAxisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool yAxisSpecified {
            get {
                return this.yAxisFieldSpecified;
            }
            set {
                this.yAxisFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="SoluiNet.GradientStopType", Namespace="http://solui.net/BrushDefinition.xsd")]
    public partial class SoluiNetGradientStopType {
        
        private string colourField;
        
        private string offsetField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string colour {
            get {
                return this.colourField;
            }
            set {
                this.colourField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string offset {
            get {
                return this.offsetField;
            }
            set {
                this.offsetField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="SoluiNet.BrushType", Namespace="http://solui.net/BrushDefinition.xsd")]
    public enum SoluiNetBrushType {
        
        /// <remarks/>
        SimpleLinearGradient,
        
        /// <remarks/>
        LinearGradient,
    }
}
