//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.7.3081.0.
// 
namespace SoluiNet.DevTools.Core.Settings {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="SoluiNet.SettingType", Namespace="http://solui.net/SettingSchema.xsd")]
    [System.Xml.Serialization.XmlRootAttribute("SoluiNet.Settings", Namespace="http://solui.net/SettingSchema.xsd", IsNullable=false)]
    public partial class SoluiNetSettingType {
        
        private SoluiNetEnvironmentType[] soluiNetEnvironmentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SoluiNet.Environment")]
        public SoluiNetEnvironmentType[] SoluiNetEnvironment {
            get {
                return this.soluiNetEnvironmentField;
            }
            set {
                this.soluiNetEnvironmentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="SoluiNet.EnvironmentType", Namespace="http://solui.net/SettingSchema.xsd")]
    public partial class SoluiNetEnvironmentType {
        
        private SoluiNetSettingEntryType[] soluiNetSettingEntryField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SoluiNet.SettingEntry")]
        public SoluiNetSettingEntryType[] SoluiNetSettingEntry {
            get {
                return this.soluiNetSettingEntryField;
            }
            set {
                this.soluiNetSettingEntryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="SoluiNet.SettingEntryType", Namespace="http://solui.net/SettingSchema.xsd")]
    public partial class SoluiNetSettingEntryType {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
}
