//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=4.7.3081.0.
// 
namespace SoluiNet.DevTools.Core.Deployment {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="SoluiNet.DeploymentConfiguration", Namespace="http://solui.net/DeploymentConfiguration.xsd")]
    [System.Xml.Serialization.XmlRootAttribute("SoluiNet.DeploymentConfiguration", Namespace="http://solui.net/DeploymentConfiguration.xsd", IsNullable=false)]
    public partial class SoluiNetDeploymentConfiguration {
        
        private SoluiNetTask[] soluiNetTaskField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SoluiNet.Task")]
        public SoluiNetTask[] SoluiNetTask {
            get {
                return this.soluiNetTaskField;
            }
            set {
                this.soluiNetTaskField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="SoluiNet.Task", Namespace="http://solui.net/DeploymentConfiguration.xsd")]
    public partial class SoluiNetTask {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SoluiNet.CopyTask", typeof(SoluiNetCopyTask))]
        [System.Xml.Serialization.XmlElementAttribute("SoluiNet.ExecuteScriptTask", typeof(SoluiNetExecuteScriptTask))]
        [System.Xml.Serialization.XmlElementAttribute("SoluiNet.TransformTask", typeof(SoluiNetTransformTask))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="SoluiNet.CopyTask", Namespace="http://solui.net/DeploymentConfiguration.xsd")]
    public partial class SoluiNetCopyTask {
        
        private string fromField;
        
        private string toField;
        
        private string ignorePatternField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string from {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string to {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ignorePattern {
            get {
                return this.ignorePatternField;
            }
            set {
                this.ignorePatternField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="SoluiNet.ExecuteScriptTask", Namespace="http://solui.net/DeploymentConfiguration.xsd")]
    public partial class SoluiNetExecuteScriptTask {
        
        private string scriptField;
        
        private bool needsElevatedRightsField;
        
        private bool needsElevatedRightsFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string script {
            get {
                return this.scriptField;
            }
            set {
                this.scriptField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool needsElevatedRights {
            get {
                return this.needsElevatedRightsField;
            }
            set {
                this.needsElevatedRightsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool needsElevatedRightsSpecified {
            get {
                return this.needsElevatedRightsFieldSpecified;
            }
            set {
                this.needsElevatedRightsFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="SoluiNet.TransformTask", Namespace="http://solui.net/DeploymentConfiguration.xsd")]
    public partial class SoluiNetTransformTask {
        
        private string pluginField;
        
        private string transformationField;
        
        private string sourceField;
        
        private string destinationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string plugin {
            get {
                return this.pluginField;
            }
            set {
                this.pluginField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string transformation {
            get {
                return this.transformationField;
            }
            set {
                this.transformationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
            }
        }
    }
}
