//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.7.3081.0.
// 
namespace SoluiNet.DevTools.Core.WebClientDefinition {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://solui.net/WebClientDefinition.xsd")]
    [System.Xml.Serialization.XmlRootAttribute("SoluiNet.WebClientDefinition", Namespace="http://solui.net/WebClientDefinition.xsd", IsNullable=false)]
    public partial class SoluiNetWebClientDefinition {
        
        private SoluiNetEndpointType[] endpointsField;
        
        private SoluiNetWebMethodType[] methodsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Endpoint", IsNullable=false)]
        public SoluiNetEndpointType[] Endpoints {
            get {
                return this.endpointsField;
            }
            set {
                this.endpointsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("WebMethod", IsNullable=false)]
        public SoluiNetWebMethodType[] Methods {
            get {
                return this.methodsField;
            }
            set {
                this.methodsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="SoluiNet.EndpointType", Namespace="http://solui.net/WebClientDefinition.xsd")]
    public partial class SoluiNetEndpointType {
        
        private string nameField;
        
        private string descriptionField;
        
        private string urlField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="SoluiNet.HttpHeaderType", Namespace="http://solui.net/WebClientDefinition.xsd")]
    public partial class SoluiNetHttpHeaderType {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="SoluiNet.WebMethodType", Namespace="http://solui.net/WebClientDefinition.xsd")]
    public partial class SoluiNetWebMethodType {
        
        private string nameField;
        
        private string descriptionField;
        
        private string requestContentField;
        
        private SoluiNetHttpMethodType[] supportedHttpMethodsField;
        
        private SoluiNetHttpHeaderType[] preparedHttpHeadersField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string RequestContent {
            get {
                return this.requestContentField;
            }
            set {
                this.requestContentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("HttpMethod", IsNullable=false)]
        public SoluiNetHttpMethodType[] SupportedHttpMethods {
            get {
                return this.supportedHttpMethodsField;
            }
            set {
                this.supportedHttpMethodsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("HttpHeader", IsNullable=false)]
        public SoluiNetHttpHeaderType[] PreparedHttpHeaders {
            get {
                return this.preparedHttpHeadersField;
            }
            set {
                this.preparedHttpHeadersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.3081.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="SoluiNet.HttpMethodType", Namespace="http://solui.net/WebClientDefinition.xsd")]
    public enum SoluiNetHttpMethodType {
        
        /// <remarks/>
        POST,
        
        /// <remarks/>
        GET,
        
        /// <remarks/>
        PUT,
        
        /// <remarks/>
        DELETE,
    }
}
