//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1586.0.
// 
namespace SoluiNet.DevTools.Core.ScriptEngine {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/SqlScript.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/SqlScript.xsd", IsNullable=false)]
    public partial class SqlScripts {
        
        private SqlScript[] sqlScriptField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SqlScript")]
        public SqlScript[] SqlScript {
            get {
                return this.sqlScriptField;
            }
            set {
                this.sqlScriptField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/SqlScript.xsd")]
    public partial class SqlScript {
        
        private string nameField;
        
        private string descriptionField;
        
        private string commandTextField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string CommandText {
            get {
                return this.commandTextField;
            }
            set {
                this.commandTextField = value;
            }
        }
    }
}
