// <copyright file="SoluiNetService.Desginer.cs" company="SoluiNet">
// Copyright (c) SoluiNet. All rights reserved.
// </copyright>

namespace SoluiNet.DevTools.Web
{
    /// <summary>
    /// The SoluiNet service.
    /// </summary>
    partial class SoluiNetService
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean used resources.
        /// </summary>
        /// <param name="disposing">True, if managed resources should be disposed; otherwise false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region generated by component designer
        /// <summary> 
        /// Required method for designer support.
        /// The content of this method shouldn't be changed by code editor.
        /// </summary>
        private void InitializeComponent()
        {
            components = new System.ComponentModel.Container();
            this.ServiceName = "SoluiNetService";
        }
        #endregion
    }
}
